[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/nlopes/slack"
  branch = "master"

[[constraint]]
  name = "github.com/alyosha/slack-utils"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
