[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.4.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[prune]
  go-tests = true
  unused-packages = true
